### ISSUE TITLE
Confirm 2009 Election Irregularities story

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/af-elections-data-story#13]
The 2009 Election Irregularities story does not seem to match the 2009 site data. This story should show: `Stations with 600 votes or more or votes to a single candidate at or above 95%.` according to the existing '09 site.

On the '09 site I see the following two districts:
<img width="822" alt="Screen Shot 2019-05-23 at 9 57 32 PM" src="https://user-images.githubusercontent.com/12634024/58337320-8a394c00-7e13-11e9-99ac-2d835a3e708e.png">
<img width="822" alt="Screen Shot 2019-05-23 at 9 57 39 PM" src="https://user-images.githubusercontent.com/12634024/58337321-8a394c00-7e13-11e9-812a-2aa6f0987e50.png">

However, on the new site the properties that are being used to generate the data story return the following:
<img width="825" alt="Screen Shot 2019-05-23 at 9 58 20 PM" src="https://user-images.githubusercontent.com/12634024/58337339-991ffe80-7e13-11e9-91fb-2c1e5d49261f.png">
<img width="825" alt="Screen Shot 2019-05-23 at 9 58 25 PM" src="https://user-images.githubusercontent.com/12634024/58337341-991ffe80-7e13-11e9-9cf2-ce4fe3ddf374.png">

@Rub21 Can we look into this? Am I simply misunderstanding the new calculation, or do we need to revisit the methodology?

**Comment by Rub21** [comment]
@LanesGood I have checked this, but there is not a good match in the number some of them match quite good, but some of them have a difference.  Maybe it is because of the data (result.sqlite), but in most of the case the differences are a couple of votes, 

- WorMayi
![image](https://user-images.githubusercontent.com/1152236/58484905-a2b5a900-8128-11e9-947e-9089f5d4245b.png)

![image](https://user-images.githubusercontent.com/1152236/58485524-d7763000-8129-11e9-8412-9c8d0bac16ad.png)
-  Gomal
![image](https://user-images.githubusercontent.com/1152236/58484955-b7923c80-8128-11e9-986a-114454bce9f0.png)
![image](https://user-images.githubusercontent.com/1152236/58485536-de9d3e00-8129-11e9-9d16-3cdc49e95f26.png)


- Nani
![image](https://user-images.githubusercontent.com/1152236/58485012-d395de00-8128-11e9-8ac4-17678810f85f.png)
![image](https://user-images.githubusercontent.com/1152236/58485166-253e6880-8129-11e9-9861-5ca860077089.png)

- Registan
![image](https://user-images.githubusercontent.com/1152236/58485142-13f55c00-8129-11e9-8932-e5e3e7d3d4f8.png)
![image](https://user-images.githubusercontent.com/1152236/58485220-3a1afc00-8129-11e9-8d69-a9323267116c.png)

[fraud-2009.csv.zip](https://github.com/developmentseed/af-elections-data-story/files/3228081/fraud-2009.csv.zip)

**Comment by LanesGood** [comment]
@Rub21 `Nari` district is a difference of over 2000 votes. This is just one out of the nearly 400 districts. The discrepancy seems problematic. Are we confident that this is the right formula? Or is the new script measuring some other feature?

**Comment by Rub21** [comment]
@LanesGood As my   understand for this, We need to get candidates  who get more or equal  to 95%  or more or equals to 600 votes in each polling station: 
https://github.com/developmentseed/af-elections-data-story/blob/master/2009/fraud-votes/index.js#L56, once I filtered that for each candidate, I am making the sum  to get the total fraud votes for each candidate per district and get the percentages

**Comment by Rub21** [comment]
@LanesGood  The results bubbles looks quite the same,  but in our case, we have much more districts. 
- [Old map](https://afghanistanelectiondata.org/election/2009/#filter/600-95-AND/country?views-mode=%20views-mode-map#layers=district_map_openlayers_7,district_map_openlayers_%208,afghanistan-ethnic&baseLayers=afghanistan-grey)
![image](https://user-images.githubusercontent.com/1152236/58712944-34225680-8387-11e9-9d5c-215819d98dd2.png)

- New map
![image](https://user-images.githubusercontent.com/1152236/58712935-2c62b200-8387-11e9-813a-0744792fcd2e.png)

**Comment by Rub21** [comment]
I also added these new attributes:   `totalFraudVotes`  and `totalFraudVotesPercentage = (totalFraudVotes / totalVotes)*100` you may need to use that ones

**Comment by LanesGood** [comment]
@Rub21 thanks hopefully this new attribute will solve the hover data issue.
